import { app, Menu, nativeImage, Tray, type NativeImage } from 'electron'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import type { VpnStatus } from '@univpn/vpn-platform'
import { Strings } from '../../../mobile/src/constants/strings'
import { vpnService } from './vpn'
import { getSettings, setSettings } from './settings'

type TrayState = 'idle' | 'connecting' | 'connected' | 'failed'

const STATE: Record<VpnStatus, TrayState> = {
  disconnected: 'idle',
  connecting: 'connecting',
  disconnecting: 'connecting',
  connected: 'connected',
  error: 'failed',
}
const TITLE: Record<TrayState, string> = {
  idle: Strings.connection.idle.title,
  connecting: Strings.connection.connecting.title,
  connected: Strings.connection.connected.title,
  failed: Strings.connection.failed.title,
}

// Icons generated by scripts/gen-tray.ts (see resources/tray).
const iconDir = app.isPackaged
  ? path.join(process.resourcesPath, 'resources', 'tray')
  : path.join(app.getAppPath(), 'resources', 'tray')

function iconFor(state: TrayState): NativeImage {
  if (process.platform === 'darwin') {
    // "Template" in the name → macOS tints it for light/dark menu bar; @2x picked automatically.
    return nativeImage.createFromPath(path.join(iconDir, `mac-${state}Template.png`))
  }
  // 16/20/32/64px ≈ 100/125/200/400% display scaling
  const img = nativeImage.createEmpty()
  for (const [size, scaleFactor] of [[16, 1], [20, 1.25], [32, 2], [64, 4]] as const) {
    img.addRepresentation({ scaleFactor, buffer: readFileSync(path.join(iconDir, `win-${state}-${size}.png`)) })
  }
  return img
}

let tray: Tray | null = null
let shown: { state: TrayState; profileId: string | null } | null = null
let profiles: { id: string; serverName: string }[] = []

async function loadProfiles(): Promise<void> {
  try {
    profiles = (await vpnService.getProfiles()).profiles
  } catch {
    profiles = [] // belum masuk / offline: tombol Sambungkan nonaktif
  }
}

async function connectPreferred(): Promise<void> {
  if (profiles.length === 0) await loadProfiles()
  const id = profiles.find((p) => p.id === getSettings().lastProfileId)?.id ?? profiles[0]?.id
  if (!id) return
  try {
    await vpnService.connect(id)
    setSettings({ lastProfileId: id })
  } catch {
    // status 'error' shows up in the next refresh()
  }
  await refresh()
}

async function refresh(): Promise<void> {
  if (!tray) return
  const state = STATE[await vpnService.status()]
  if (state === 'connected' && profiles.length === 0) await loadProfiles() // masuk setelah aplikasi dibuka
  const profileId = vpnService.getCurrentProfileId()
  if (shown?.state === state && shown.profileId === profileId) return
  shown = { state, profileId }

  const active = state === 'connected' || state === 'connecting'
  const location = profiles.find((p) => p.id === profileId)?.serverName
  tray.setImage(iconFor(state))
  tray.setToolTip(`${Strings.app.name} — ${TITLE[state]}`)
  tray.setContextMenu(
    Menu.buildFromTemplate([
      { label: TITLE[state], enabled: false },
      ...(location && active ? [{ label: location, enabled: false }] : []),
      { type: 'separator' },
      active
        ? { label: 'Putuskan', click: () => void vpnService.disconnect().then(refresh) }
        : { label: 'Sambungkan', click: () => void connectPreferred() },
      { label: `Buka ${Strings.app.name}`, click: () => showWindow() },
      { type: 'separator' },
      {
        label: 'Keluar',
        click: () => {
          // jangan tinggalkan terowongan menyala setelah aplikasi ditutup
          void vpnService.disconnect().catch(() => {}).finally(() => app.quit())
        },
      },
    ])
  )
}

let showWindow: () => void = () => {}

export function createTray(onOpen: () => void): void {
  showWindow = onOpen
  tray = new Tray(iconFor('idle'))
  tray.on('click', () => tray?.popUpContextMenu())
  void loadProfiles().then(refresh)
  setInterval(() => void refresh(), 1000)
}
